plugins {
id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
id 'com.gradleup.shadow' version '9.2.2'
id 'maven-publish'
}

group = project.maven_group
version = project.mod_version

base {
archivesName = project.archives_base_name
}

repositories {
maven {
name = "Modrinth"
url = "https://api.modrinth.com/maven"
}
maven {
name = "Fabric"
url = "https://maven.fabricmc.net/"
}
mavenCentral()
}

loom {
splitEnvironmentSourceSets()

mods {
    "flashback-redroided" {
        sourceSet sourceSets.main
        sourceSet sourceSets.client
    }
}

}

dependencies {
minecraft "com.mojang:minecraft:${minecraft_version}"
mappings loom.officialMojangMappings()
modImplementation "net.fabricmc:fabric-loader:${loader_version}"
modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

modCompileOnly "maven.modrinth:4das1Fjq:${flashback_version}"

shadow files("ffmpeg/javacpp.jar")
shadow files("ffmpeg/javacpp-android-arm64.jar")
shadow files("ffmpeg/ffmpeg.jar")
shadow files("ffmpeg/ffmpeg-android-arm64-gpl.jar")

shadow files("deps/imgui-binding-1.92.jar")
shadow files("deps/imgui-java-natives-android.jar")

}

def modVersion = providers.gradleProperty("mod_version")

processResources {
inputs.property("version", modVersion)

filesMatching("fabric.mod.json") {
    expand(version: modVersion.get())
}

}

java {
withSourcesJar()
sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
options.release = 21
}

jar {
archiveBaseName.set(project.archives_base_name)

from("LICENSE") {
    rename { "${it}_flashback-redroided" }
}

}

shadowJar {
archiveBaseName.set("${project.archives_base_name}-1.21-1.21.11")
archiveVersion.set(project.version.toString())
destinationDirectory.set(layout.buildDirectory.dir("intermediates"))

from(sourceSets.main.output)
from(sourceSets.client.output)

configurations = [project.configurations.shadow]

exclude("LICENSE")
exclude("LICENSE.txt")

}

tasks.named("assemble") {
dependsOn(shadowJar)
}

tasks.named("remapJar") {
    dependsOn(shadowJar)
    inputFile.set(shadowJar.archiveFile)
    archiveBaseName.set("${project.archives_base_name}-1.21.11")
}